# cleanup
rm -rf obj_dir
rm -f f1_light.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_light.sv --exe f1_light_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_light.mk Vf1_light

# run executable simulation file
obj_dir/Vf1_light